ARG START_IMAGE

FROM ${START_IMAGE}
MAINTAINER Gabriele Pongelli <gabriele.pongelli@gmail.com>

ENV PYTHON_VERSION=3.11
ENV PYTHON_COMPLETE_VERSION=3.11.1

USER root

# install packages to compile pillow and the other python packages on ARM
RUN yum install -y \
        autoconf \
        automake \
        bash \
        bzip2-devel \
        libffi-devel \
        libtool \
        openssl-devel \
        platform-python-devel \
        tree \
        wget

RUN mkdir -p /opt/build_python/installed \
    && cd /opt/build_python \
    && wget https://www.python.org/ftp/python/${PYTHON_COMPLETE_VERSION}/Python-${PYTHON_COMPLETE_VERSION}.tar.xz > /dev/null 2>&1 \
    && tar xvf Python-${PYTHON_COMPLETE_VERSION}.tar.xz > /dev/null 2>&1 \
    && cd Python-${PYTHON_COMPLETE_VERSION} \
    && ./configure --enable-shared --enable-optimizations --disable-test-modules --prefix=/opt/build_python/installed \
    && make altinstall \
    && tree -apugC /opt/build_python/installed

ENV PATH "/opt/build_python/installed/bin/:$PATH"
ENV LD_LIBRARY_PATH "/opt/build_python/installed/lib/:$LD_LIBRARY_PATH"

RUN rm -rdf /opt/build_python/Python-${PYTHON_COMPLETE_VERSION}.tar.xz \
    && rm -rdf /opt/build_python/Python-${PYTHON_COMPLETE_VERSION}/ \
    && ln -s /opt/build_python/installed/bin/python${PYTHON_VERSION} /usr/local/bin/python3 \
    && ln -s /opt/build_python/installed/bin/python${PYTHON_VERSION}-config /usr/local/bin/python3-config \
    && ln -s /opt/build_python/installed/bin/pip${PYTHON_VERSION} /usr/local/bin/pip3 \
    && python3 --version


CMD ["bash"]
