name: Build Manylinux with compiled Python

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: read
  id-token: write


jobs:
  docker_build:
    name: Build on ${{ matrix.os }} - py${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8, 3.9, "3.10", "3.11" ]
        # https://github.com/actions/runner-images list of images
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    outputs:
      python_no_dot_version: ""

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # setup cross compilation action https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # login to docker action, to then push (in this case into python script) https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setting python version for docekr build
        uses: actions/github-script@v6
        id: set_python_version_build
        with:
          script: |
            core.setOutput('python_no_dot_version', '${{ matrix.python-version }}'.replaceAll(/[/.]/g, ''));

      # in case of static docker image building, https://github.com/marketplace/actions/docker-build-push-action
      #  github action is better  ( https://github.com/docker/build-push-action )
      - uses:mr-smithers-excellent/docker-build-push@v5
        name: build docker images
        with:
          image: gpongelli/manylinux_python
          tags: manylinux_2_28_x64_py${{ steps.set_python_version_build.outputs.python_no_dot_version }}
          registry: docker.io
          dockerfile: Dockerfile_2_28_x64_py${{ steps.set_python_version_build.outputs.python_no_dot_version }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          platform: x86_64

      #  upload readme.md to dockerhub https://github.com/peter-evans/dockerhub-description
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: gpongelli/manylinux_python
